# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "blowfish"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

# mainSections = ["section1", "section2"]
# robots = ""

disableImageOptimization = false

# defaultBackgroundImage = "IMAGE.jpg" # used as default for background images 
defaultBackgroundImage = "img/cover.png"

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = true

[header]
  layout = "fixed-fill" # valid options: basic, fixed

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = false

[homepage]
  layout = "hero" # valid options: page, profile, hero, card, background, custom
  homepageImage = "img/cover.png" # used in: hero, and card
  showRecent = false
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "posts"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = false # only used when layout equals background

[article]
  showDate = true
  showViews = true
  showLikes = true
  showDateUpdated = false
  showAuthor = true
  showHero = true
  heroStyle = "big" # valid options: basic, big, background, thumbAndBackground
  #layoutBackgroundBlur = false # only used when heroStyle equals background or thumbAndBackground
  #layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = true
  editURL = "https://github.com/terraformbuch/website/tree/main/content/"
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true 
  showAuthorsBadges = true 
  showWordCount = false
  showSummary = true
  sharingLinks = [ "linkedin", "twitter", "reddit", "email" ]

[list]
  showHero = true
  heroStyle = "basic" # valid options: basic, big, background, thumbAndBackground
  #layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  #layoutBackgroundHeaderSpace = false # only used when heroStyle equals background
  showBreadcrumbs = false
  showSummary = false
  showViews = true
  showLikes = true
  showTableOfContents = true
  showCards = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = ["taxonomy","term"]

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "basic" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  cardView = false

[term]
  showHero = true
  heroStyle = "basic" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  #groupByYear = false
  cardViewScreenWidth = false
  cardView = true

[firebase]
  # apiKey = "XXXXXX"
  # authDomain = "XXXXXX"
  # projectId = "XXXXXX"
  # storageBucket = "XXXXXX"
  # messagingSenderId = "XXXXXX"
  # appId = "XXXXXX"
  # measurementId = "XXXXXX"
  #apiKey = "AIzaSyBgBgtoCIKUjZThoaoVyjm2hlOuG15BoU4"
  #authDomain = "tibeer.firebaseapp.com"
  #projectId = "tibeer"
  #storageBucket = "tibeer.appspot.com"
  #messagingSenderId = "580540384286"
  #appId = "1:580540384286:web:2111811e128e1224bf1a0f"
  #measurementId = "G-YTHENVSB1F"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[buymeacoffee]
  # identifier = ""
  # globalWidget = true
  # globalWidgetMessage = "Hello"
  # globalWidgetColor = "#FFDD00"
  # globalWidgetPosition = "Right"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
